apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secretName }}-spc
spec:
  provider: azure
  secretObjects: 
    - secretName: {{ .Values.secretName }}
      type: {{ .Values.secretType | default "Opaque" }}
      data:
        {{- range .Values.secrets }}
        - objectName: {{ .name }}
          key: {{ .key }}
        {{- end }}
  parameters:
    keyvaultName: {{ .Values.keyvaultName }}
    userAssignedIdentityID: {{ .Values.clientId }}
    useVMManagedIdentity: "true" 
    tenantId: {{ .Values.tenantId }}
    objects: |
      array:
        {{- range .Values.secrets }}
        - |
          objectName: {{ .name }}
          objectType: {{ .type }}
          {{- if .version }}
          objectVersion: {{ .version }}
          {{- end }}
          {{- if .encoding }}
          objectEncoding: {{ .encoding }}
          {{- end }}
        {{- end }}